name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build application
        run: python build.py

        # Esto toma el contenido de dist/TrackSIM_Tools y crea el archivo TrackSIMTools.zip en la raíz de dist/
      - name: Compress Directory to ZIP
        shell: pwsh
        run: |
          Compress-Archive -Path dist/TrackSIM_Tools -DestinationPath dist/TrackSIMTools.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create Release and Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --title "${{ github.ref_name }}" --notes "Release for version ${{ github.ref_name }}" dist/TrackSIM_Tools.zip
